CREATE TABLE "core_svc"."support_ticket_attachments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticket_id" uuid NOT NULL,
	"message_id" uuid,
	"r2_key" text NOT NULL,
	"mime" text,
	"size_bytes" integer,
	"original_filename" text,
	"uploaded_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "core_svc"."support_ticket_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticket_id" uuid NOT NULL,
	"author_type" text NOT NULL,
	"author_id" uuid NOT NULL,
	"body" text NOT NULL,
	"is_internal_note" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "support_ticket_messages_author_type_check" CHECK ("core_svc"."support_ticket_messages"."author_type" in ('user','admin'))
);
--> statement-breakpoint
CREATE TABLE "core_svc"."support_tickets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"number" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "core_svc"."support_tickets_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"workspace_id" uuid NOT NULL,
	"author_id" uuid NOT NULL,
	"subject" text NOT NULL,
	"description" text NOT NULL,
	"scope_type" text DEFAULT 'general' NOT NULL,
	"scope_project_id" uuid,
	"status" text DEFAULT 'open' NOT NULL,
	"priority" text DEFAULT 'normal' NOT NULL,
	"assigned_admin_id" uuid,
	"last_reply_at" timestamp with time zone,
	"last_reply_by" text,
	"first_responded_at" timestamp with time zone,
	"resolved_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "support_tickets_scope_check" CHECK ("core_svc"."support_tickets"."scope_type" in ('general','project','billing','account','technical')),
	CONSTRAINT "support_tickets_status_check" CHECK ("core_svc"."support_tickets"."status" in ('open','pending','resolved','closed')),
	CONSTRAINT "support_tickets_priority_check" CHECK ("core_svc"."support_tickets"."priority" in ('low','normal','high','urgent'))
);
--> statement-breakpoint
ALTER TABLE "core_svc"."support_ticket_attachments" ADD CONSTRAINT "support_ticket_attachments_ticket_id_support_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "core_svc"."support_tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core_svc"."support_ticket_attachments" ADD CONSTRAINT "support_ticket_attachments_message_id_support_ticket_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "core_svc"."support_ticket_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core_svc"."support_ticket_messages" ADD CONSTRAINT "support_ticket_messages_ticket_id_support_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "core_svc"."support_tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "support_ticket_attachments_ticket_id_idx" ON "core_svc"."support_ticket_attachments" USING btree ("ticket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "support_ticket_attachments_r2_key_uq" ON "core_svc"."support_ticket_attachments" USING btree ("r2_key");--> statement-breakpoint
CREATE INDEX "support_ticket_messages_ticket_id_idx" ON "core_svc"."support_ticket_messages" USING btree ("ticket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "support_tickets_number_uq" ON "core_svc"."support_tickets" USING btree ("number");--> statement-breakpoint
CREATE INDEX "support_tickets_workspace_id_idx" ON "core_svc"."support_tickets" USING btree ("workspace_id");--> statement-breakpoint
CREATE INDEX "support_tickets_author_id_idx" ON "core_svc"."support_tickets" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "support_tickets_status_idx" ON "core_svc"."support_tickets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "support_tickets_assigned_admin_idx" ON "core_svc"."support_tickets" USING btree ("assigned_admin_id");